"""expense created at

Revision ID: 4d804be61d26
Revises: 4a5bc5ef610c
Create Date: 2024-07-26 12:55:00.303385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d804be61d26'
down_revision: Union[str, None] = '4a5bc5ef610c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_column('expenses', 'created_at')
    # ### end Alembic commands ###
